"""Add default value to votes

Revision ID: 5d55a41f38ca
Revises: 3a50e05197ee
Create Date: 2024-09-18 13:20:08.377711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d55a41f38ca'
down_revision = '3a50e05197ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Candidates', schema=None) as batch_op:
        batch_op.alter_column('votes',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Candidates', schema=None) as batch_op:
        batch_op.alter_column('votes',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
