"""Add votes column to Candidate model

Revision ID: 77e5f9ac1766
Revises: eb588ed99e9d
Create Date: 2024-09-17 15:49:00.922939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77e5f9ac1766'
down_revision = 'eb588ed99e9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('votes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Candidates', schema=None) as batch_op:
        batch_op.drop_column('votes')

    # ### end Alembic commands ###
